plugins {
    id 'com.android.application'
}

android {
    namespace 'com.timerlock.secure'
    compileSdk 35

    defaultConfig {
        applicationId 'com.timerlock.secure'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '4.0.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
